title: Lejondary
logo: /assets/img/LejondaryPFP.jpg
  #email: person@address.com
description: Under Contruction!
favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
