title: Lejondary
logo: /assets/img/LejondaryPFP.jpg
  #email: person@address.com
description: Under Contruction!
favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/Lejondary
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/jonathanphari

navigation:
  - name: About
    link: ./index.html
  - name: Goals
  - name: Journal
    link: ./another-page.html
